sudo: false
language: node_js
env:
  global:
    - DISPLAY=:99.0
#    - JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
#before_install:
#  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR
before_script:
  - npm install jpm -g
#  - cd ..
#  - get-firefox -cvep linux
#  - cd $TRAVIS_BUILD_DIR
script:
  - jpm test